version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-terraform
    user: root
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Para que Jenkins use Docker del host
      - ~/.aws:/root/.aws                          # Para credenciales AWS locales
      - ./jenkins_home:/var/jenkins_home           # Persistencia y configuración personalizada
      - ./plugins.txt:/usr/share/jenkins/ref/plugins.txt:ro
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

volumes:
  jenkins_home:
